language: node_js
node_js:
- '11'
- '10'
- '9'
- '8'
cache:
  directories:
  - node_modules
before_install:
- cp ./tests/api.json ~/.saram.conf
- npm i -g typescript
- npm i
script:
- npm test
- npm run docs
notifications:
  slack:
    secure: UoaR/peqUJhOek0/hPQ0CtsMt9EAv9WinOwmkd/tOasTuS2FmZPYoknIMBgi4F+A0TcFNyeVPp/USp9rzuWqLeGy5uw5dxaw+c4MN/Ltbi3/E+rGrPr7oSwlEiV2bXLvS3+pYeSGu1aJxDhxs2/S0S56D51P8IbrMbfZ9/zgRQ1QRKGwvWGSkuA9sPdXqXRCXHIRwXo1x0b4IkvEzPh2QmNgcqRFWah1UYQcGsgRalbr0+KHGdO6frLGZyCjztSmTnGcenTS3sHRUOhKb8iT1szZrDW9vFlF9nARfea7owY69FocPDILy4+Ys5dLCtmap3dRZG7zsSpPFO4RYoAsvrOFNgeSqqsnLH/HqZFF1t4LKa83Y0ZHQoSO5eC1Baycer2O9FX6j66mZU2QoLFbnYnUUASNA7uxjSmN8TEdKXtwax8tK1bOnqwFsnJI0ovbXszGT1soJ1NN5DIYSLfb7p5WiifyGRDaaI+bSP4Hhk4UGcpiBHsMYyOpzpstU039RT7R2/ucDP8xZEdWyLuLGHnvogEfhTaZvkTufi72jmJ/6nIny/ty486a9RrfdSsakTOlMhaxV2csiljU/gkySKAVvkSmQ3QHkWONSXfiGZSsCbZKwhVn7M7AZ6bUmJsStAxmeN99byFY4BA+RUS3Exq1L7Et4R0G2Av1vTeGe5U=
deploy:
  - provider: s3
    access_key_id:
      secure: yCMg1jnP+g/0rx63IF8MiAvCv+d6RGhEUi/KNlIe5bo3qiW1Doyv44zAbQemV8NbBczNYEMx7B6uUYWONrqQwNi43dPla8UocBaMAaWYDu6xIzvYFf9YKOlWwr1Zo4t0+ImfMPHgG6S1Hj1nRaMA0lQYDxoVKkV2gqW7jH+3vZItphjRHWkV0KUss0kAox46XQfMlJOXeKo9P4if8hvGBNiXhoG2vd94S789tJdJ52ffbvO5G8cokrn7HQjsKTbtV4zc5VutWa2lULLlWGo8ljxWXwToXv8HXlWsuDP7WLpNJGVIURsboEJqSGMr3tu6FGHe9azB+8q8gqsRpEtsLbfxHe0Ukl/2Mmt8zoZUyV22nnOr/EVM6t8WOEFlKolFyuUQ6qBN9r0BLh5XTEs+1YvAg+kIb4ZawdZdaESUrc22vPm/Qr8bECBbiIcKWrSdRgsA8wr4avnHZ64QgNWyOI8LT1Qj2BsT0/ord9yJlpP2FIGobQmPx5uBErbx1bpOAkc0+ExiLPquitn66b4KjSlPR0yKuGlYfMCx4Rw7y6Jglcz2kiGU0/jMAcXaI9ik3FeNTqVZtRwOy9gAH/iTC1+YIJXFnqxcJbDjqwpu+/KhoSeqnM3wRIPw/WxeVwcVJS63SxEvExvb6kGOGOnClqaF7nnFpeNLbEdxZieK9PE=
    secret_access_key:
      secure: VFhXpdzQF6lcOkeuL3q5XEiUqLB8kcl1GGcW89rIFAnfC9w+Apq+46zGcJzGShS+7Alk7c5z05mimahBupuXoC4Ywvp1yOkMTsZI4mdaAT5IKNLqYgXafElRZIMctp24wHAXpN0Vz9z3Wk+43d/er7F60JpyuH+OlbWOrT8qIumzktucY+RnBmHNadnCrK1n/9YrzkX79u38C8IPP2uUnhtgSQhD4V11UXquwc86LJMxX/jj6DSm15VA+A1NzH6640jFum4kEs1wRJezRCO7oDWFeWs9RCGqzBN0AHqm5Y9pcA1ni7gBDlqOaPmtcZA69WaDcuH6tRswE8ePy5MdL6BOzVNPlvMZnP+XXCT3Ls5P3mHnAjqEnmOZNs4JP75V+1FS7RuZEOtK7D28fEUIuoa7haXSPDoXWsVZXTd0X1Vob73j4ViSdrO2mYZnlX6sMbkgx5T/LrL6cXMJTyMLFT4JOGyuaVgqlbm6KuFEzP0tjkgG4P1qvPu1o2BtmIiXlNv8lf+l/VQEYzTAeX2rgz12mZL3TGO8gEIxqbPwBDUNHl4yptTvF2rh60eXTYXqnTV0IAAbl4fGq+i+ss5ihKNXyew6uJhm2eFIPjS6hiHJ2HaASn/fvSb+bBi+6ba2M6+0OcaZzKxOdE6dLOKYnwgJ/EfzQPPEqccULeMCk3s=
    bucket: saramjs.docs.securisec.net
    local-dir: docs
    acl: public_read
    on:
      repo: securisec/saramJs
  - provider: npm
    email: securisecdev@gmail.com
    api_key:
      secure: 62UnJaip82UsupkV1cOV8KRmy2W/gxFziN/+osljPjV2SUQs5H+5+k0kwI10bP3abYW4zDHsxyoiY19A3yUY3ZyG+0CIm7+5bP2Tjo8xSPv4XEC+1qe/LLbABs5cy6TPn6ETAOivrm93ZhTx2XIB4rrLk3InJvxUQlK5XyqTNmgFYP+V4MujaCDwlk3hHD54vRBf9Q60vFYiAClRIG3pQzZdXh2NxfBOgC1SOQ/VnEImAl0svV0f8qnBGA3bRXeq71gqjGqZa5r5J7kLy5xyYWyGzVmzfiLHNK+stPmLuh1DAvW4wQfpyvt9Hm+zTYtZfDVjACSBzNYadXX2kjPLoS1WerTJJn/PFAsNgS3GckZ2yymUPcStrTxXC0t5KTTmIgXddgKHB9/v4hNSyzHH7xDYhIUjf+pSwXo74cEOjI0IiUlt/tPOCdzbqkJSVovjrNBd3iFwK2is5trIFN6weRdxJsxspdI+J2vSYHWTYo+2qGaO9XogEzl2ExT+dYCV5+NSvWqkYcaFlSqEccwXBhscU0c1Po6EmliKHevCsZjm52s05fIe00B9LBgXvrUi6nLJGqXOUOpjRsLVL2QASUFo/SOTKYCv4uNAJKyJb5e3+LMYeSmg50U6xuv5KHt8jzLrAKYc8yZF35WbUiiI8ttXYtDVJo2LuVOazENMVT4=
    on:
      tags: true
      repo: securisec/saramJs
    skip_cleanup: true